# Generated by Django 5.0.3 on 2024-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('ItemName', models.CharField(max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Quantity', models.IntegerField()),
                ('ItemID', models.BigIntegerField()),
                ('ImageURL', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Cart',
                'managed': True,
            },
        ),
    ]
