# Generated by Django 4.1.5 on 2023-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Sponsors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
