# Generated by Django 5.0.3 on 2024-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.BinaryField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.BinaryField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Drivers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsor_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.BinaryField(max_length=255)),
                ('sponsor_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Sponsors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=255)),
                ('password', models.BinaryField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('login_attempts', models.IntegerField(default=0)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
