# Generated by Django 5.0.3 on 2024-03-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
