# Generated by Django 5.0.3 on 2024-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_token_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
