# Generated by Django 5.0.3 on 2024-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_points', models.FloatField()),
            ],
            options={
                'db_table': 'Points',
                'managed': True,
            },
        ),
    ]
